server:
  port: 8089
spring:
  application:
    name: location-service
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    